# ----------------------------------------------------------------
# Maintainer: Andrin Schälin, aschalin@ethz.ch
# Last Updated: 2025-06-14
# Description: Configuration for motion planning Python API
# Based on the MoveIt! configuration for the Franka Emika Panda robot
# ----------------------------------------------------------------


planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/moveit_cpp/planning_scene_monitor"
  publish_planning_scene_topic: "/moveit_cpp/publish_planning_scene"
  monitored_planning_scene_topic: "/moveit_cpp/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  pipeline_names: ["ompl", "pilz_industrial_motion_planner", "chomp"]

plan_request_params:
  planning_attempts: 5
  planning_pipeline: ompl
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0


ompl_rrtc:  
  plan_request_params:  
    planning_attempts: 5 
    planning_pipeline: ompl  
    planner_id: "RRTConnectConfigDefault"  
    max_velocity_scaling_factor: 1.0  
    max_acceleration_scaling_factor: 1.0 
    planning_time: 2.0  
  

pilz_lin:
  plan_request_params:
    planning_attempts: 5
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: "PTP"
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0
    planning_time: 1.6
  

chomp_planner:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: chomp
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0
    planning_time: 1.5
